// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5eucLDV6-XboAyuZdK_KGt2UvGleFEoc',
    appId: '1:915189876414:android:da4ff795f27f075ee3c0ef',
    messagingSenderId: '915189876414',
    projectId: 'e-shop-89f6a',
    storageBucket: 'e-shop-89f6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHaI2t8IMc5n5lRz4iNh0DSKvtwNmoqco',
    appId: '1:915189876414:ios:4217d3a39e765e25e3c0ef',
    messagingSenderId: '915189876414',
    projectId: 'e-shop-89f6a',
    storageBucket: 'e-shop-89f6a.firebasestorage.app',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgd7aQ0hCn1U78x2KJFvveSKEPAo9Ik5g',
    appId: '1:915189876414:web:40e5b933b91ecbd5e3c0ef',
    messagingSenderId: '915189876414',
    projectId: 'e-shop-89f6a',
    authDomain: 'e-shop-89f6a.firebaseapp.com',
    storageBucket: 'e-shop-89f6a.firebasestorage.app',
  );

}